#!/bin/zsh

# make sure you're root
if ! [[ $(id -u) -eq 0 ]]; then sudo "$0"; exit; fi

# grab mutter
apt source mutter
apt build-dep mutter

# target aquired warlock
cd $(ls -dr mutter*/ | head -1)
sed  -i '/case XkbNewKeyboard/d' src/backends/x11/meta-backend-x11.c
dpkg-buildpackage -rfakeroot -uc -b
cd ..

# set the correct version (6 for older 7 for newer)
ver=$(ls libmutter* | head -1 | cut -d"-" -f"2")

# install the update bish
dpkg -i libmutter-$ver-0_*.deb
dpkg -i mutter*.deb
dpkg -i gir1.2-mutter*.deb
apt-mark hold libmutter-$ver-0 gir1.2-mutter mutter-common

# do a version check
apt list --installed | grep "mutter"

# remove all our hard work
find . -iname "*mutter*" ! -iname "buildmutter" -exec rm -rf {} \; 2> /dev/null