#!/bin/zsh

# make sure you're root
if ! [[ $(id -u) -eq 0 ]]; then sudo "$0"; exit; fi

# grab mutter
apt source mutter
apt build-dep mutter

# target aquired warlock
cd $(ls -dr mutter*/ | head -1)
sed  -i '/case XkbNewKeyboard/d' src/backends/x11/meta-backend-x11.c
dpkg-buildpackage -rfakeroot -uc -b
cd ..

# install the update bish
dpkg -i libmutter-6-0_*.deb
dpkg -i gir1.2-mutter*.deb
apt-mark hold libmutter-6-0 gir1.2-mutter

# do a version check
apt list --installed | grep -E "(libmutter-6-0|gir1.2-mutter)"