#!/bin/bash

yt_args="--force-ipv4 -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --match-filter 'duration < 7200' --download-archive .archive.txt -a .download.txt --yes-playlist -o '%(uploader)s - %(title)s.%(ext)s'"

#####################################################################
# Flush .mp4 files
# [ -f | --flush ]
#
# Flush out files (with confirmation).
#####################################################################
if [[ "$1" =~ ^(-f|--flush)$ ]]; then
	a=$(find . -iname "*.mp4" | wc -l)
	echo "Are you sure you want to flush $a files?"
	echo -n "[y/N]: "; read junk
	if [[ "$junk" == [yY] ]]; then find . -iname "*.mp4" -type f -exec rm -v {} \;; fi
	echo "--- Press [Enter] to exit ---"; read -s; exit
fi


#####################################################################
# Yes automatically
# [ -y | --yes ]
#
# Implies yes on asking.
# You could "yes|./CheckAll" but who's counting anyways?
#####################################################################
if [[ "$1" =~ ^(-y|--yes)$ ]]; then
	for f in *; do
		if [[ -d "$f" ]]; then
			echo "Checking $f..."
			cd "$f"
			youtube-dl $yt_args
			rm *.jpg *.part 2> /dev/null
			cd ..
		fi
	done
fi

#####################################################################
# Main function
#
# checks for each directory and does a yt-mass in each one
#####################################################################
for f in *; do
	if [[ -d "$f" ]]; then
		junk=
		echo "Check $f for unarchived videos?"
		echo -n "[y/N]: "; read junk
		if [[ "$junk" == [yY] ]]; then
			echo "Checking $f..."
			cd "$f"
			youtube-dl $yt_args
			rm *.jpg *.part 2> /dev/null
			cd ..
		fi
	fi
done