# shell variables
CASE_SENSITIVE="false"
DISABLE_AUTO_TITLE="true"
HISTFILE="~/.zsh_history"
HYPHEN_INSENSITIVE="true"
ZSH_DISABLE_COMPFIX="true"
 
# cursebreaker
export CURSEBREAKER_PATH='/Applications/World of Warcraft/_retail_/World of Warcraft.app'

# prompt
if [[ $(id -u) == 0 ]]; then
	PROMPT="%F{132}%B%~%b %F{cyan}#%f "
else
	PROMPT="%F{132}%B%~%b %F{cyan}➜%f "
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
elif [[ $(uname) == "Darwin" ]]; then
	export EDITOR='open -a "Visual Studio Code - Insiders"'
else
	export EDITOR='code'
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# PATH for ~/.local/bin
export PATH="$PATH:/usr/local/opt/python/libexec/bin:$HOME/.local/bin"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
plugins=(colorize github sudo ubuntu macos vscode zsh-autosuggestions)
VSCODE=code-insiders

# architecture shorthand
alias ar="arch -x86_64 $1"

# cursebreaker wow updates
alias cb="a=$(pwd); cd ~/Documents/GitHub/CurseBreaker; git pull; python3 CurseBreaker.py; cd $a"

# install (apt) shortcut
alias i="sudo apt install $1"

# make / make install shortcuts
alias m="make"
alias mi="sudo make install"

# set keyboard color
alias msi="sudo msi-perkeyrgb -m gs65 -s $1"

# reload zsh config
alias reload="source ~/.zshrc"

# rename tv shows
alias rename-tv='rename -v '"'"'s/.*(S[0-9]*E[0-9]*).*\.(avi|mkv|mp4)/$1\.$2/i'"'"' *'
alias rename-tv-x='rename -v '"'"'s/.*?([0-9]*)[xX]([0-9]*).*?(avi|mkv|mp4)/S$1E$2.$3/i'"'"' *'

# tmux config
alias tmuxcfg="$EDITOR $HOME/.tmux.conf"

# check for and install updates
alias update="sudo apt update && sudo apt upgrade && sudo apt autoremove"

# wine: disable logging
export WINEDEBUG="-all"

# weather from wttr.in (metric)
alias weather="curl 'wttr.in/?m'"

# youtube-dl shortcuts
alias yt="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --external-downloader axel --external-downloader-args '-n 10 -a' -o '%(title)s.%(ext)s' $1"
alias yt-mp3="youtube-dl -ciwx --audio-format mp3 $1"
alias yt-pl="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt --yes-playlist -o '%(uploader)s - %(title)s.%(ext)s' $1"
alias yt-chan="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt -o '%(title)s.%(ext)s' $1"
alias yt-mass="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt -a download.txt --yes-playlist -o '%(uploader)s - %(title)s.%(ext)s'"

# zsh config
alias zshcfg="$EDITOR ~/.zshrc"

# load extra scripts
source $ZSH/oh-my-zsh.sh

if [[ $(uname) == "Darwin" ]]; then
	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2> /dev/null
else
	source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2> /dev/null
fiexport PATH=$PATH:/Users/dustinsabecky/.spicetify
