# shell variables
CASE_SENSITIVE="false"
DISABLE_AUTO_TITLE="true"
HISTFILE="$ZDOTDIR/.zsh_history"
HYPHEN_INSENSITIVE="true"
ZSH_DISABLE_COMPFIX="true"

# prompt
if [[ $(id -u) == 0 ]]; then
	PROMPT="%F{magenta}%B%~%b %F{cyan}#%f "
else
	PROMPT="%F{magenta}%B%~%b %F{cyan}➜%f "
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='code'
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
plugins=(colorize github sudo ubuntu vscode)
VSCODE=code-insiders

# set keyboard color
alias msi="sudo msi-perkeyrgb -m gs65 -s $1"

# reload zsh config
alias reload="source $ZDOTDIR/.zshrc"

# rename tv shows
alias rename-tv='rename -v '"'"'s/.*(S[0-9]*E[0-9]*).*\.(avi|mkv|mp4)/$1\.$2/'"'"' *'

# check for and install updates
alias update="sudo apt update && sudo apt upgrade && sudo apt autoremove"

# youtube-dl shortcuts
alias yt="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --external-downloader axel --external-downloader-args '-n 10 -a' -o '%(title)s.%(ext)s' $1"
alias yt-pl="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt --yes-playlist -o '%(uploader)s - %(title)s.%(ext)s' $1"
alias yt-chan="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt -o '%(title)s.%(ext)s' $1"
alias yt-mass="youtube-dl -ciw -f best --add-metadata --write-thumbnail --embed-thumbnail --download-archive archive.txt -a download.txt --yes-playlist -o '%(uploader)s - %(title)s.%(ext)s'"

# zsh config
alias zshcfg="$EDITOR $ZDOTDIR/.zshrc"

# load extra scripts
source $ZSH/oh-my-zsh.sh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2> /dev/null
